version: "3"
services:
  solr:
    ports:
      # do not forward in production
      - "8983:8983"
    tty: true
    stdin_open: true
    image: solr
    environment:
      - SOLR_HEAP=2g
    command:
      - solr-precreate
      - domains
    volumes:
      - solrdata:/var/solr
  solrapi:
    build: .
    ports:
      - "8080:8080"

volumes:
  solrdata: